/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //defaultSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  introSidebar: [
    'intro',
    {
      type: 'category',
      label: '專案',
      link: {
        type: 'generated-index',
        description: "我們發起的專案"
      },
      items: [
          'projects/infra_labs',
          'projects/glossary',
      ],
    },
    {
      type: 'category',
      label: '持續徵稿',
      link: {
        type: 'generated-index',
        description: "中英講者徵稿"
      },
      items: [
          'cfp/cfp-en',
          'cfp/cfp-zh-tw'
      ],
    }
  ],
};

module.exports = sidebars;
